/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'content' : string,
  'seoTags' : Array<string>,
  'suggestedTitle' : string,
  'confidenceScore' : bigint,
  'keywords' : Array<string>,
  'summary' : string,
  'timestamp' : bigint,
  'category' : string,
  'readTimeMinutes' : bigint,
}
export interface FeedbackEntry {
  'correctCategory' : string,
  'isHelpful' : boolean,
  'analysisTimestamp' : bigint,
  'correctedKeywords' : Array<string>,
}
export interface FeedbackStats {
  'totalFeedback' : bigint,
  'helpfulCount' : bigint,
  'categoryCorrections' : Array<[string, bigint]>,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'estimateAnalysisConfidence' : ActorMethod<[string], bigint>,
  'getAllUsersAnalysisCounts' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getAnalysisCount' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeedbackStats' : ActorMethod<[], FeedbackStats>,
  'getHistory' : ActorMethod<[], Array<AnalysisResult>>,
  'getMostConfidentAnalysis' : ActorMethod<[], [] | [AnalysisResult]>,
  'getMyFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAnalysis' : ActorMethod<
    [
      string,
      Array<string>,
      string,
      Array<string>,
      bigint,
      string,
      string,
      bigint,
      bigint,
    ],
    undefined
  >,
  'submitFeedback' : ActorMethod<
    [bigint, boolean, string, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];