/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'email' : IDL.Text,
});
export const FeedbackStats = IDL.Record({
  'totalFeedback' : IDL.Nat,
  'helpfulCount' : IDL.Nat,
  'categoryCorrections' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const AnalysisResult = IDL.Record({
  'content' : IDL.Text,
  'seoTags' : IDL.Vec(IDL.Text),
  'suggestedTitle' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'keywords' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'timestamp' : IDL.Nat,
  'category' : IDL.Text,
  'readTimeMinutes' : IDL.Nat,
});
export const FeedbackEntry = IDL.Record({
  'correctCategory' : IDL.Text,
  'isHelpful' : IDL.Bool,
  'analysisTimestamp' : IDL.Nat,
  'correctedKeywords' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'estimateAnalysisConfidence' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAllUsersAnalysisCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getAnalysisCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeedbackStats' : IDL.Func([], [FeedbackStats], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getMostConfidentAnalysis' : IDL.Func(
      [],
      [IDL.Opt(AnalysisResult)],
      ['query'],
    ),
  'getMyFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAnalysis' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'submitFeedback' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'email' : IDL.Text,
  });
  const FeedbackStats = IDL.Record({
    'totalFeedback' : IDL.Nat,
    'helpfulCount' : IDL.Nat,
    'categoryCorrections' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const AnalysisResult = IDL.Record({
    'content' : IDL.Text,
    'seoTags' : IDL.Vec(IDL.Text),
    'suggestedTitle' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'keywords' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'timestamp' : IDL.Nat,
    'category' : IDL.Text,
    'readTimeMinutes' : IDL.Nat,
  });
  const FeedbackEntry = IDL.Record({
    'correctCategory' : IDL.Text,
    'isHelpful' : IDL.Bool,
    'analysisTimestamp' : IDL.Nat,
    'correctedKeywords' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'estimateAnalysisConfidence' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAllUsersAnalysisCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getAnalysisCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeedbackStats' : IDL.Func([], [FeedbackStats], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getMostConfidentAnalysis' : IDL.Func(
        [],
        [IDL.Opt(AnalysisResult)],
        ['query'],
      ),
    'getMyFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAnalysis' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'submitFeedback' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };